title = "LocalSlate Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist for testing and environment folders"
paths = [
    '''\.venv''',
    '''data/.*''',
    '''frontend/.*''',
    '''tests/.*'''
]
